version: "3"

services:
  app:

    restart: on-failure
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_CONNECTION_STRING: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_HOST_PORT}/${DB_NAME}
      NODE_ENV: production
    ports:
      - ${SERVER_HOST_PORT}:${SERVER_PORT}

  postgres:

    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
