version: "3"

services:
  app:

    restart: on-failure
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      NODE_ENV: production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgres:

    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER2: postgres
      POSTGRES_PASSWORD2: password
      POSTGRES_DB2: db_name
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
